const SEPOLIA_CHAIN_ID = 11155111;
const POLYGON_CHAIN_ID = 137;

const NETWORK_CONFIG = {
  [SEPOLIA_CHAIN_ID]: {
    name: "sepolia",
    ethUsdPriceFeed: "0x694AA1769357215DE4FAC081bf1f309aDC325306",
  },
  [POLYGON_CHAIN_ID]: {
    name: "polygon",
    ethUsdPriceFeed: "0xF9680D99D6C9589e2a93a78A04A279e509205945",
  },
};

const DEVELOPMENT_CHAINS = ["hardhat", "localhost"];

const DECIMALS = 8;
const INITIAL_ANSWER = 200000000000;

const SEPOLIA_RPC_URL = process.env.SEPOLIA_RPC_URL;
const PRIVATE_KEY = process.env.PRIVATE_KEY;
const ETHERSCAN_API_KEY = process.env.ETHERSCAN_API_KEY;
const COINMARKETCAP_API_KEY = process.env.COINMARKETCAP_API_KEY;

module.exports = {
  SEPOLIA_CHAIN_ID,
  POLYGON_CHAIN_ID,
  NETWORK_CONFIG,
  DEVELOPMENT_CHAINS,
  DECIMALS,
  INITIAL_ANSWER,
  SEPOLIA_RPC_URL,
  PRIVATE_KEY,
  ETHERSCAN_API_KEY,
  COINMARKETCAP_API_KEY,
};
